version: 2
sphinx:
  configuration: conf.py
  fail_on_warning: false
build:
  os: ubuntu-lts-latest
  tools:
    python: "3.12"
jobs:
    build:
      html:
        - mkdir -p $READTHEDOCS_OUTPUT/html
        - cp -a html/. $READTHEDOCS_OUTPUT/html/