# .readthedocs.yaml
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  commands:
    # 直接复制HTML文件到输出目录
    - mkdir -p $READTHEDOCS_OUTPUT/html/
    - cp -r html/* $READTHEDOCS_OUTPUT/html/